### ISSUE TITLE
Idea Tracker

### ISSUE THREAD

**Issue by DannielK** [DannielK/DannielK.github.io#2]
**Following comments are added ideas to implement**

**Comment by DannielK** [comment]
- [ ] Sticky sidebar content timeline scroller that skips to sections
- [ ] Add downloadable resume by contact info
- [ ] Visual skill list showing relative mastery %
